insert into authors (id, first_name, last_name) values (1, 'Isabeau', 'Gorvette');
insert into authors (id, first_name, last_name) values (2, 'Feodora', 'Cristobal');
insert into authors (id, first_name, last_name) values (3, 'Lammond', 'McMackin');
insert into authors (id, first_name, last_name) values (4, 'Daisey', 'Bawdon');
insert into authors (id, first_name, last_name) values (5, 'Manda', 'Sammut');
insert into authors (id, first_name, last_name) values (6, 'Fraser', 'Jeduch');
insert into authors (id, first_name, last_name) values (7, 'Heinrick', 'Storm');
insert into authors (id, first_name, last_name) values (8, 'Granthem', 'Hanniger');
insert into authors (id, first_name, last_name) values (9, 'Lowell', 'O''Carroll');
insert into authors (id, first_name, last_name) values (10, 'Biddy', 'Skyppe');
insert into authors (id, first_name, last_name) values (11, 'Fan', 'Tollit');
insert into authors (id, first_name, last_name) values (12, 'Klarika', 'Bastian');
insert into authors (id, first_name, last_name) values (13, 'Dale', 'Astbury');
insert into authors (id, first_name, last_name) values (14, 'Zebadiah', 'Tenwick');
insert into authors (id, first_name, last_name) values (15, 'Claudianus', 'St. Quintin');
insert into authors (id, first_name, last_name) values (16, 'Diann', 'Cardenosa');
insert into authors (id, first_name, last_name) values (17, 'Chan', 'Flescher');
insert into authors (id, first_name, last_name) values (18, 'Baxie', 'Peris');
insert into authors (id, first_name, last_name) values (19, 'Whitaker', 'Le Fleming');
insert into authors (id, first_name, last_name) values (20, 'Trefor', 'Henriques');
insert into authors (id, first_name, last_name) values (21, 'Nesta', 'Vitet');

insert into books (id, price, price_old, title, author_id) values (1, 856, 3885, 'Andalax', 1);
insert into books (id, price, price_old, title, author_id) values (2, 1112, 1939, 'Lotlux', 11);
insert into books (id, price, price_old, title, author_id) values (3, 1674, 1344, 'Fix San', 8);
insert into books (id, price, price_old, title, author_id) values (4, 1340, 3413, 'It', 1);
insert into books (id, price, price_old, title, author_id) values (5, 1219, 2274, 'Asoka', 7);
insert into books (id, price, price_old, title, author_id) values (6, 1479, 2516, 'Gembucket', 15);
insert into books (id, price, price_old, title, author_id) values (7, 2868, 1095, 'Solarbreeze', 19);
insert into books (id, price, price_old, title, author_id) values (8, 2515, 2000, 'Bamity', 17);
insert into books (id, price, price_old, title, author_id) values (9, 2557, 3323, 'Viva', 1);
insert into books (id, price, price_old, title, author_id) values (10, 2862, 1987, 'Y-find', 8);
insert into books (id, price, price_old, title, author_id) values (11, 1484, 1351, 'Bitwolf', 14);
insert into books (id, price, price_old, title, author_id) values (12, 561, 2132, 'Domainer', 4);
insert into books (id, price, price_old, title, author_id) values (13, 1363, 3160, 'Quo Lux', 21);
insert into books (id, price, price_old, title, author_id) values (14, 1872, 1032, 'Redhold', 3);
insert into books (id, price, price_old, title, author_id) values (15, 559, 2246, 'Lotlux', 20);
insert into books (id, price, price_old, title, author_id) values (16, 2583, 2777, 'Bitchip', 1);
insert into books (id, price, price_old, title, author_id) values (17, 2561, 3926, 'Tresom', 9);
insert into books (id, price, price_old, title, author_id) values (18, 2033, 3395, 'Fixflex', 21);
insert into books (id, price, price_old, title, author_id) values (19, 2042, 2199, 'Sonair', 13);
insert into books (id, price, price_old, title, author_id) values (20, 2423, 1633, 'Subin', 15);
insert into books (id, price, price_old, title, author_id) values (21, 1729, 3993, 'Pannier', 12);
